"""Generate a Doxyfile for a Zephyr-style Doxygen project.

Usage:
    python configure_doxygen.py <output_dir> <pages_dir> [options]

Creates a Doxyfile in <output_dir> pointing to page files in <pages_dir>.
Also copies the Zephyr CSS into the output directory structure.
"""
import os
import sys
import argparse
import shutil


DOXYFILE_TEMPLATE = """# Doxyfile - Zephyr-style multi-page documentation
# Generated by zephyr-doxygen-docs skill

DOXYFILE_ENCODING      = UTF-8
PROJECT_NAME           = "{project_name}"
PROJECT_NUMBER         = "{project_number}"
PROJECT_BRIEF          = "{project_brief}"
PROJECT_LOGO           = {project_logo}

OUTPUT_DIRECTORY       = {output_dir}
OUTPUT_LANGUAGE        = Chinese
MARKDOWN_SUPPORT       = YES
TOC_INCLUDE_HEADINGS   = 6

INPUT                  = {pages_dir}
RECURSIVE              = NO
FILE_PATTERNS          = *.md
IMAGE_PATH             = {image_path}

USE_MDFILE_AS_MAINPAGE = {mainpage_path}

GENERATE_HTML          = YES
HTML_OUTPUT            = html
HTML_EXTRA_STYLESHEET  = {css_path}
HTML_COLORSTYLE        = LIGHT

GENERATE_TREEVIEW      = YES
TREEVIEW_WIDTH         = 320
DISABLE_INDEX          = YES
FULL_SIDEBAR           = NO

GENERATE_LATEX         = NO

SHOW_FILES             = NO
SHOW_NAMESPACES        = NO

WARNINGS               = YES
WARN_IF_UNDOCUMENTED   = NO
QUIET                  = YES
"""


def configure(workspace_root, pages_dir, project_name="My Project",
              project_version="", project_brief="", logo_path="",
              image_paths=None, overwrite=True):
    """Create Doxyfile and copy CSS assets."""

    doxy_output = os.path.join(workspace_root, "doxygen_output")
    os.makedirs(doxy_output, exist_ok=True)

    # Copy CSS
    css_src = os.path.join(os.path.dirname(__file__), "..", "assets", "zephyr.css")
    css_dst = os.path.join(workspace_root, "doxygen_custom.css")
    if os.path.exists(css_src):
        shutil.copy(css_src, css_dst)
        print(f"  Copied Zephyr CSS to {css_dst}")

    # Normalize paths for Doxyfile (use forward slashes, absolute)
    pages_dir_abs = os.path.abspath(pages_dir).replace("\\", "/")
    mainpage = f"{pages_dir_abs}/mainpage.md"
    css_abs = os.path.abspath(css_dst).replace("\\", "/")
    logo_val = f'"{os.path.abspath(logo_path).replace(chr(92), "/")}"' if logo_path else ""
    output_abs = os.path.abspath(doxy_output).replace("\\", "/")
    img_path = " ".join(
        f'"{os.path.abspath(p).replace(chr(92), "/")}"'
        for p in (image_paths or [])
    )

    content = DOXYFILE_TEMPLATE.format(
        project_name=project_name,
        project_number=project_version,
        project_brief=project_brief,
        project_logo=logo_val,
        output_dir=output_abs,
        pages_dir=pages_dir_abs,
        mainpage_path=mainpage,
        css_path=css_abs,
        image_path=img_path,
    )

    doxyfile = os.path.join(workspace_root, "Doxyfile")
    with open(doxyfile, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  Created Doxyfile at {doxyfile}")

    return doxyfile


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate Zephyr-style Doxyfile')
    parser.add_argument('workspace', help='Workspace root for Doxyfile + CSS')
    parser.add_argument('pages_dir', help='Directory containing page .md files')
    parser.add_argument('--project-name', default='My Project')
    parser.add_argument('--project-version', default='')
    parser.add_argument('--project-brief', default='')
    parser.add_argument('--logo', default='', help='Path to project logo PNG')
    parser.add_argument('--images', nargs='*', default=[], help='Image search paths')
    args = parser.parse_args()

    configure(args.workspace, args.pages_dir,
              args.project_name, args.project_version, args.project_brief,
              args.logo, args.images)
    print("\nDone. Run 'doxygen Doxyfile' in the workspace to build.")
